### ISSUE TITLE
Add ability to edit cluster

### ISSUE THREAD

**Issue by fbricon** [jlandersen/vscode-kafka#25]
There's currently no way to edit an existing cluster (change the friendly name, add a broker, correct credentials). Deleting/recreating a cluster seems like an overkill alternative.

**Comment by angelozerr** [comment]
When I try to connect to my cloudkafka, I spend so many times to delete, recreate the cluster configuration (because I'm so newbie with kafka) . I think this issue is important.

**Comment by angelozerr** [comment]
To fix this issue, there are 2 solutions:

 * create a custom Webview which manages cluster fields.
 * store the settings in the vscode settings.json. @jlandersen is there any reason why you don't store cluster settings in the vscode settings.json? I ask this question because https://vscode-sqltools.mteixeira.dev/features/sessions-and-multiple-connections#session-files does that, see https://github.com/mtxr/vscode-sqltools/blob/7c382e8e02b77e7df6147cbc67d19339aabd3a10/packages/extension/package.json#L550

Storing cluster in settings.json will avoid developing custom UI for editing clusters.

**Comment by jlandersen** [comment]
@angelozerr originally it actually was in settings.json. The reason to move it out was mostly to make it more manageable from the UI side (adding/removing multiple). I do see in the workspace API it is possible to update those values programmatically now (https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration). I am open for using settings.json. Ideally we'd come to a model where it is possible to merge both own configurations as well as any potentially shared ones in a workspace. How that would look I don't have an immediate answer to as an array of connections in settings would simply be overridden per how vscode merges the different levels of settings.

**Comment by fbricon** [comment]
Fixed with #193
